version: '3'
services:
  crapi-secured.42crunch.test:
    image: 42crunch/apifirewall:latest
    ports:
      - '4241:443'
      - '8880:8880'
    volumes:
      - ./storage/apifirewall/ssl:/opt/guardian/conf/ssl
      - ./storage/apifirewall/logs:/opt/guardian/logs
    command: ["/bin/squire", "-platform", "services.42crunch.com:8001", "-debug"]
    environment:
      - PROTECTION_TOKEN=${PROTECTION_TOKEN}
      - LISTEN_PORT=443
      - TARGET_URL=http://host.docker.internal:8888
      - LISTEN_SSL_CERT=mycert.pem
      - LISTEN_SSL_KEY=private.pem
      - LISTEN_NO_TLS=true
      - SERVER_NAME=crapi-secured.42crunch.test:4241
      - GUARDIAN_NODE_NAME=Local-Firewall
      - GUARDIAN_INSTANCE_NAME=Local-Firewall
      - LOG_LEVEL=DEBUG
      - LOG_DESTINATION=PLATFORM+STDOUT
